// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBADDDHbcgxpy7ietbIu4Hq0fy2eqJsXOY',
    appId: '1:645135066332:web:fad05b9628fd36f8400019',
    messagingSenderId: '645135066332',
    projectId: 'kahoot-clone-39e22',
    authDomain: 'kahoot-clone-39e22.firebaseapp.com',
    databaseURL: 'https://kahoot-clone-39e22-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kahoot-clone-39e22.firebasestorage.app',
    measurementId: 'G-LLXGMPDJ2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvRlC5ZFepMdzjoZE1crbIteoL-LoofSc',
    appId: '1:645135066332:android:b3834469f4daaff2400019',
    messagingSenderId: '645135066332',
    projectId: 'kahoot-clone-39e22',
    databaseURL: 'https://kahoot-clone-39e22-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kahoot-clone-39e22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTd-PFvDHgUAn4crtcibZI8riaAJq6ZYQ',
    appId: '1:645135066332:ios:4912e775714b897c400019',
    messagingSenderId: '645135066332',
    projectId: 'kahoot-clone-39e22',
    databaseURL: 'https://kahoot-clone-39e22-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kahoot-clone-39e22.firebasestorage.app',
    iosClientId: '645135066332-f71ao6256jbiuq3srql4lbh54pgisjj6.apps.googleusercontent.com',
    iosBundleId: 'com.example.kahootClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTd-PFvDHgUAn4crtcibZI8riaAJq6ZYQ',
    appId: '1:645135066332:ios:4912e775714b897c400019',
    messagingSenderId: '645135066332',
    projectId: 'kahoot-clone-39e22',
    databaseURL: 'https://kahoot-clone-39e22-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kahoot-clone-39e22.firebasestorage.app',
    iosClientId: '645135066332-f71ao6256jbiuq3srql4lbh54pgisjj6.apps.googleusercontent.com',
    iosBundleId: 'com.example.kahootClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBADDDHbcgxpy7ietbIu4Hq0fy2eqJsXOY',
    appId: '1:645135066332:web:0e2885871ee94f1b400019',
    messagingSenderId: '645135066332',
    projectId: 'kahoot-clone-39e22',
    authDomain: 'kahoot-clone-39e22.firebaseapp.com',
    databaseURL: 'https://kahoot-clone-39e22-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kahoot-clone-39e22.firebasestorage.app',
    measurementId: 'G-07V7MLZ5LK',
  );
}
